apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.service.name }}
          servicePort: {{ .Values.service.internalPort }}
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - {{ .Values.host }}
status:
  loadBalancer:
    ingress:
    - ip: {{ .Values.ingress.ip }}
